"""
modules/web/zap_wrap.py
OWASP ZAP baseline scan wrapper for Aegis Scanner (web layer).

apt's `zaproxy` package on this box ships the ZAP daemon/GUI (zap.sh) but
not the `zap-baseline.py` helper script — that script is part of ZAP's
official Docker image and assumes ZAP's own bundled directory layout, not a
bare apt install. Rather than depend on a script that isn't actually present
on a real Kali install, this module drives the same underlying scan
directly: start the ZAP daemon headless, spider the target (traditional
spider only — no active/attack payloads, matching zap-baseline.py's own
"passive scan" scope), wait for the passive scanner to finish analysing
whatever the spider found, pull the alerts back over ZAP's REST API via the
official `zapv2` client (requirements.txt), and shut the daemon down.

This does NOT go through error_handler.run_tool() — run_tool() models "one
subprocess, wait for it to exit," but this module needs to start a
long-lived daemon, talk to it over HTTP while it runs, and only then tell it
to stop. It follows the same never-raises contract error_handler.py
documents (everything is wrapped in try/except, a KeyboardInterrupt is
treated the same way run_tool() treats it — see error_handler.py's module
docstring) and logs through the same log_tool_start/success/failure calls
run_tool() would have made.
"""

import shutil
import time

from modules.utils.config import get_timeout

# config.py is gitignored, so a per-user copy predating these keys is a real
# possibility — unset means "spawn a local daemon", i.e. today's behaviour.
try:
    from modules.utils.config import ZAP_HOST, ZAP_PORT
except ImportError:
    ZAP_HOST, ZAP_PORT = None, 8090
from modules.utils.logger import (
    log_tool_start, log_tool_success, log_tool_failure, log_finding,
)
from modules.utils.display import (
    print_info, print_success, print_warning, print_error,
)

_ZAP_HOST = "127.0.0.1"
_ZAP_PORT = 8090
_ZAP_STARTUP_TIMEOUT = 60.0
_POLL_INTERVAL = 2.0

# Known install locations for zap.sh across Kali's zaproxy package layouts,
# checked before falling back to a PATH lookup.
_ZAP_SH_CANDIDATES = (
    "/usr/share/zaproxy/zap.sh",
    "/usr/share/owasp-zap/zap.sh",
)

# ZAP's own "risk" rating maps onto this project's four-tier scale and onto
# zap-baseline.py's original WARN/FAIL/INFO status vocabulary, so a report
# generated by either code path reads the same way.
_RISK_SEVERITY = {"High": "HIGH", "Medium": "MEDIUM", "Low": "LOW", "Informational": "LOW"}
_RISK_STATUS = {"High": "FAIL", "Medium": "WARN", "Low": "INFO", "Informational": "INFO"}


def _find_zap_sh():
    for candidate in _ZAP_SH_CANDIDATES:
        import os
        if os.path.isfile(candidate):
            return candidate
    return shutil.which("zap.sh")


def _build_url(target: str, port: int, use_https: bool) -> str:
    if target.startswith(("http://", "https://")):
        return target.rstrip("/")
    scheme = "https" if use_https else "http"
    default_port = 443 if use_https else 80
    host = target if port == default_port else f"{target}:{port}"
    return f"{scheme}://{host}"


def _clean(value) -> str:
    """ZAP returns "" for fields it has nothing for; normalise to a stripped
    string so the caller can test one way.

    Internal newlines are collapsed to single spaces. ZAP's `reference` is a
    newline-separated LIST of URLs, and its descriptions wrap across lines;
    left as-is those newlines land in the middle of a report's field layout
    and break the finding card apart. Nothing is dropped — the URLs are
    joined, not truncated.
    """
    if value is None:
        return ""
    return " ".join(str(value).split())


def _cwe_id(alert: dict) -> str:
    """ZAP's cweid, or "" when it does not apply.

    ZAP uses -1 (and occasionally 0) as its own "not applicable" sentinel —
    verified against real alerts, where Session Management Response
    Identified carries cweid -1. Rendering that as "CWE -1" would invent a
    weakness class that does not exist, so the sentinel is dropped and the
    field reports as undetermined instead.
    """
    raw = _clean(alert.get("cweid"))
    if not raw:
        return ""
    try:
        if int(raw) <= 0:
            return ""
    except ValueError:
        return ""
    return f"CWE-{raw}"


def _dedupe_alerts(alerts: list) -> list:
    """Collapse ZAP's per-URL alerts to one row per (rule, name).

    ZAP reports the same rule once per matching URL, so a 25-alert response
    is commonly 8 distinct issues. The first occurrence's URL/evidence/param
    are kept as the exemplar and the number of affected URLs is recorded, so
    collapsing does not hide the breadth of a finding.

    Everything carried here is ZAP's own output. Fields ZAP left empty stay
    empty rather than being filled with a plausible-looking default: for a
    passive baseline scan `attack` is empty on every alert (there are no
    attack payloads to report), and `param`/`evidence` are populated on only
    some rules — verified against a real 25-alert run, see smoke_test8 §3.1.
    """
    findings = []
    seen = {}
    for a in alerts:
        risk = a.get("risk", "Informational")
        rule_id = str(a.get("pluginId", "0"))
        name = (a.get("alert") or "unknown").strip()
        key = (rule_id, name)
        if key in seen:
            entry = seen[key]
            url = _clean(a.get("url"))
            if url and url not in entry["_urls"]:
                entry["_urls"].append(url)
                entry["url_count"] = len(entry["_urls"])
            continue
        url = _clean(a.get("url"))
        entry = {
            "rule_id": rule_id,
            "name": name,
            "status": _RISK_STATUS.get(risk, "INFO"),
            "severity": _RISK_SEVERITY.get(risk, "LOW"),
            "confidence": _clean(a.get("confidence")),
            "description": _clean(a.get("description")),
            "solution": _clean(a.get("solution")),
            "reference": _clean(a.get("reference")),
            "url": url,
            "param": _clean(a.get("param")),
            "evidence": _clean(a.get("evidence")),
            "attack": _clean(a.get("attack")),
            "method": _clean(a.get("method")),
            "cwe": _cwe_id(a),
            "url_count": 1 if url else 0,
            "_urls": [url] if url else [],
        }
        seen[key] = entry
        findings.append(entry)

    for entry in findings:
        entry.pop("_urls", None)
    return findings


def _apply_auth(zap, auth) -> None:
    """
    Install each of the run's credentials as a ZAP "replacer" rule, so every
    request the daemon makes — spider and passive scan alike — carries them.

    The replacer API is used rather than ZAP's full authentication/session-
    management context because the credential here is already a finished
    session token: there is no login form to script, no session to
    re-establish, and the correct behaviour is simply "add this header to
    everything". A context would be a much larger, more fragile
    configuration to express the same thing.

    Never raises. A ZAP build without the replacer add-on is a reason to
    scan unauthenticated with a warning, not a reason to lose the scan —
    and the warning matters, because ZAP silently returning an anonymous
    view inside a run labelled authenticated is precisely the failure this
    is meant to make visible.

    The credential VALUE is never logged here, only the header NAME — see
    modules/utils/auth.py.
    """
    if auth is None or not getattr(auth, "enabled", False):
        return

    headers = auth.headers()
    if not headers:
        return

    installed = []
    for index, header in enumerate(headers):
        name, _, value = header.partition(":")
        name, value = name.strip(), value.strip()
        if not name or not value:
            continue
        try:
            zap.replacer.add_rule(
                description=f"aegis-auth-{index}",
                enabled=True,
                matchtype="REQ_HEADER",
                matchregex=False,
                matchstring=name,
                replacement=value,
            )
            installed.append(name)
        except Exception as exc:
            print_warning(
                f"[ZAP] could not set the '{name}' request header on the daemon "
                f"session ({exc}) — ZAP is scanning UNAUTHENTICATED"
            )

    if installed:
        print_info(
            f"[ZAP] authenticated session: {', '.join(installed)} set on every request"
        )


def _clear_auth(zap, auth) -> None:
    """
    Remove the replacer rules _apply_auth() installed.

    Only matters for a shared daemon (ZAP_HOST), which outlives the scan: a
    credential left installed on it would be sent to whatever target the
    next scan points at. That is a credential-disclosure bug, not an
    untidiness, which is why it is cleaned up explicitly rather than left
    to the daemon's own lifecycle.

    Never raises.
    """
    if auth is None or not getattr(auth, "enabled", False):
        return
    for index in range(len(auth.headers())):
        try:
            zap.replacer.remove_rule(f"aegis-auth-{index}")
        except Exception as exc:
            print_warning(
                f"[ZAP] could not remove the aegis-auth-{index} replacer rule "
                f"from the shared daemon ({exc}) — remove it manually, or "
                "restart the container, before scanning a different target"
            )


def run_zap_baseline(target: str, port: int = 80, use_https: bool = False,
                     auth=None) -> dict:
    """
    Run a ZAP baseline-equivalent (spider + passive scan, no active attack
    payloads) against `target`'s web service.

    Local daemon, or a remote/containerised one
    -------------------------------------------
    With config.ZAP_HOST unset — the default — this spawns a local zap.sh
    daemon exactly as it always has, and behaviour is unchanged.

    With ZAP_HOST set (typically the container in docker/zap/), it connects
    to that already-running daemon instead and never spawns or stops
    anything. That is what makes `docker compose restart zap` a real fix for
    the add-on corruption class of failure documented in WRITEUP.md §3.1:
    the container's ~/.ZAP profile is disposable, so a restart is
    guaranteed to produce a clean one, rather than reusing the same
    half-written add-on on disk that broke the previous run.

    Parameters
    ----------
    target    : str   host / IP (a full http(s):// URL is also accepted)
    port      : int   web service port (default 80)
    use_https : bool  scan over TLS
    auth      : AuthConfig | None  credentials for an authenticated scan.
                      Applied to the daemon session as a replacer rule
                      before the spider runs, so every request ZAP makes
                      (spider and passive scan alike) carries them. None
                      leaves the session exactly as before.

    Returns
    -------
    dict:
        target      : str
        port        : int
        findings    : list[dict]  {rule_id, name, status, severity,
                                  confidence, description, solution,
                                  reference, url, param, evidence, attack,
                                  method, cwe, url_count}
                                  Every one of these is ZAP's own output.
                                  Fields ZAP supplied nothing for are ""
                                  and are reported as undetermined rather
                                  than guessed.
        raw_output  : str         short human-readable summary
        error       : str | None  human-readable failure reason, if any

    Never raises. A missing ZAP install (no zap.sh found), a daemon that
    doesn't come up in time, or an unreachable target all come back as
    error set + findings empty.
    """
    log_tool_start(target, "zaproxy")

    result = {"tool": "zaproxy", "target": target, "port": port, "findings": [], "raw_output": "", "error": None, "skipped": False}
    url = _build_url(target, port, use_https)

    # A configured ZAP_HOST means the daemon is somebody else's process
    # (the docker/zap container, or a shared instance) — so zap.sh does not
    # need to exist on this host at all, and looking for it would refuse to
    # run a scan that would have worked perfectly well.
    remote_host = ZAP_HOST
    zap_sh = None
    if not remote_host:
        zap_sh = _find_zap_sh()
        if not zap_sh:
            err = (
                "zap.sh not found — OWASP ZAP is not installed on this host "
                "(expected under /usr/share/zaproxy/). Either install it, or "
                "set ZAP_HOST in .env to point at a ZAP daemon (see docker/zap/)"
            )
            result["error"] = err
            log_tool_failure(target, "zaproxy", err)
            print_error(f"[ZAP] {err}")
            return result

    try:
        from zapv2 import ZAPv2
    except ImportError:
        err = "python-owasp-zap-v2.4 (zapv2) is not installed — see requirements.txt"
        result["error"] = err
        log_tool_failure(target, "zaproxy", err)
        print_error(f"[ZAP] {err}")
        return result

    import subprocess

    timeout = get_timeout("zaproxy")
    start = time.time()
    proc = None
    zap = None

    host = remote_host or _ZAP_HOST
    zap_port = ZAP_PORT if remote_host else _ZAP_PORT

    try:
        if remote_host:
            # Nothing is spawned and, crucially, nothing is stopped in the
            # finally block either — this daemon outlives the scan and is
            # not ours to terminate.
            print_info(f"[ZAP] Using the ZAP daemon at {host}:{zap_port} (ZAP_HOST is set)")
        else:
            print_info(f"[ZAP] Starting ZAP daemon on {host}:{zap_port}")
            proc = subprocess.Popen(
            [
                zap_sh, "-daemon",
                "-host", _ZAP_HOST, "-port", str(_ZAP_PORT),
                "-config", "api.disablekey=true",
                # ZAP's default daemon startup checks online for newer
                # add-on versions and silently downloads/replaces them —
                # slow, network-dependent, and if the process is ever
                # killed mid-download (a timeout, a skip keypress) it
                # leaves the on-disk add-on half-written, so every
                # subsequent start fails with "zip END header not found"
                # for spider/pscan/ascanrules and the daemon never becomes
                # API-ready. Pinning to the add-ons apt already installed
                # avoids both the startup delay and that failure mode.
                "-config", "autoupdate.checkOnStart=false",
                "-config", "autoupdate.installScannerRules=false",
                "-config", "autoupdate.installAddonUpdates=false",
                "-config", "autoupdate.reportAlphaAddons=false",
                "-config", "autoupdate.reportBetaAddons=false",
            ],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )

        proxy = {"http": f"http://{host}:{zap_port}", "https": f"http://{host}:{zap_port}"}
        zap = ZAPv2(apikey=None, proxies=proxy)

        ready = False
        while time.time() - start < _ZAP_STARTUP_TIMEOUT:
            try:
                zap.core.version
                ready = True
                break
            except Exception:
                time.sleep(1.0)
        if not ready:
            if remote_host:
                raise RuntimeError(
                    f"no ZAP daemon answered at {host}:{zap_port} within "
                    f"{_ZAP_STARTUP_TIMEOUT:.0f}s — is the container running? "
                    "(docker compose up -d zap)"
                )
            raise RuntimeError(f"ZAP daemon did not become ready within {_ZAP_STARTUP_TIMEOUT:.0f}s")

        _apply_auth(zap, auth)

        print_info(f"[ZAP] Spidering {url}")
        scan_id = zap.spider.scan(url)
        while int(zap.spider.status(scan_id)) < 100:
            if time.time() - start > timeout:
                raise TimeoutError(f"ZAP spider exceeded the {timeout:.0f}s budget")
            time.sleep(_POLL_INTERVAL)

        print_info(f"[ZAP] Passive-scanning {url}")
        while int(zap.pscan.records_to_scan) > 0:
            if time.time() - start > timeout:
                raise TimeoutError(f"ZAP passive scan exceeded the {timeout:.0f}s budget")
            time.sleep(_POLL_INTERVAL)

        alerts = zap.core.alerts(baseurl=url)
        findings = _dedupe_alerts(alerts)
        result["findings"] = findings
        result["raw_output"] = f"{len(alerts)} raw alert(s), {len(findings)} unique after dedupe"

        log_tool_success(target, "zaproxy", time.time() - start)
        if findings:
            for f in findings:
                log_finding(target, {
                    "type": "zap_finding", "port": port,
                    "rule_id": f["rule_id"], "name": f["name"], "status": f["status"],
                    "url": f["url"], "param": f["param"], "cwe": f["cwe"],
                    "url_count": f["url_count"],
                })
                print_success(f"[ZAP] [{f['status']}] {f['name']} ({f['rule_id']})")
            print_info(f"[ZAP] {url} — {len(findings)} alert(s)")
        else:
            print_warning(f"[ZAP] {url} — scan completed, no alerts")

    except KeyboardInterrupt:
        # result["skipped"] must be set alongside the error, not just the
        # error: every profile counts a tool as FAILED when it carries an
        # error and is not marked skipped, so omitting this reports a
        # deliberate user skip as a tool failure. This is the same
        # skip-flag propagation bug previously fixed across the 15
        # run_tool()-based wrappers; zap_wrap.py drives a long-lived
        # daemon over HTTP instead of a subprocess, so it replicates
        # run_tool()'s contract by hand and was missed by that pass.
        result["skipped"] = True
        result["error"] = "skipped by user (Ctrl+C)"
        log_tool_failure(target, "zaproxy", result["error"])
        print_warning(f"[ZAP] baseline scan skipped for {url}")

    except Exception as e:
        err = str(e)
        result["error"] = err
        log_tool_failure(target, "zaproxy", err)
        print_error(f"[ZAP] baseline scan failed for {url} — {err}")

    finally:
        # Shut down ONLY a daemon this call started. A configured ZAP_HOST
        # daemon is shared and long-lived — the container, or an instance
        # someone else is using — and shutting it down here would kill it
        # after the first port of the first scan, leaving every later
        # invocation to fail with "no ZAP daemon answered". The local-spawn
        # path is unchanged and still always shuts its own daemon down.
        if zap is not None and not remote_host:
            try:
                zap.core.shutdown()
            except Exception:
                pass
        elif zap is not None and remote_host:
            # A shared daemon outlives this scan, so the credential headers
            # installed on it must not: without this, the next scan through
            # the same daemon would silently carry this scan's credentials
            # to a different target. Best-effort — a failure here is
            # reported, never raised, because the scan itself is complete.
            _clear_auth(zap, auth)

        if proc is not None:
            try:
                proc.terminate()
                proc.wait(timeout=10)
            except Exception:
                try:
                    proc.kill()
                except Exception:
                    pass

    return result


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print_error("Usage: python -m modules.web.zap_wrap <target> [port] [https]")
        sys.exit(1)

    tgt = sys.argv[1]
    prt = int(sys.argv[2]) if len(sys.argv) > 2 else 80
    https = len(sys.argv) > 3 and sys.argv[3].lower() in ("https", "true", "1", "yes")

    print_info(f"Running ZAP baseline against {tgt}:{prt} (https={https})...")
    out = run_zap_baseline(tgt, port=prt, use_https=https)
    for item in out["findings"]:
        print_info(f"  [{item['status']}] {item['name']}")
    print_info(f"Error: {out['error'] or 'none'}")
